#!/bin/sh

case $BLOCK_BUTTON in
	2) notify-send "🔈 Sound: $(amixer get Master | grep 'Front Left:' | awk '{print $6}' | tr -d '[]')" && amixer set Master toggle > /dev/null 2>&1 ;;
	3) pavucontrol ;;
	4) notify-send "🔊: $(amixer get Master | grep 'Front Left:' | awk '{print $5}' | tr -d '[]')" && amixer set Master 5%+ > /dev/null 2>&1 ;;
	5) notify-send "🔉: $(amixer get Master | grep 'Front Left:' | awk '{print $5}' | tr -d '[]')"&& amixer set Master 5%- > /dev/null 2>&1 ;;

esac

amixer get Master | grep 'Front Left:' | awk '{print $5 " - " $6}' | tr -d '[]'
